config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'info/index'
  get 'contacts/new'
  
  resources :ayudantes
  resources :contacts, only: [:new , :create]

   root 'welcome#index'

end

app/models/ayudante.rb
class Ayudante < ActiveRecord::Base 

	

	validates_format_of :nombre, :with => /\A[a-zA-Z\s]+\z/ , allow_blank: true
	validates :nombre , :presence => {:message => "Campo obligatorio"}
	validates_format_of :apellido, :with => /\A[a-zA-Z\s]+\z/ , allow_blank: true
	validates :apellido , :presence => {:message => "Campo obligatorio"}
	validates :rut, :uniqueness => {:message => "ya ingresado anteriormente"} , allow_blank: true
	validates :rut, :presence => {:message => "Campo obligatorio"}
	validates :rut, :rut => {:message => "no es valido"} , allow_blank: true
	validates :email , :presence => {:message => "Campo obligatorio"}
	validates :email, email_format: { message: "no es correcto" } , allow_blank: true
	validates :asignatura, :presence => {:message => "tiene campo vacio"}
	validates :carrera, :presence => {:message => "tiene campo vacio"}
	
end

app/models/contact.rb
class Contact < MailForm::Base
	

	attribute :nombre
	attribute :email
	attribute :mensaje

	validates_format_of :nombre, :with => /\A[a-zA-Z\s]+\z/ , allow_blank: true
	validates :nombre , :presence => {:message => "Campo obligatorio"}
	validates :email , :presence => {:message => "Campo obligatorio"}
	validates :email, email_format: { message: "no es correcto" } , allow_blank: true
	validates :mensaje , :presence => {:message => "Campo obligatorio"}

	def headers 
	{
	   	:subject => "Contact Form",
	   	:to => "ariielo23@hotmail.com",
		:from => %("#{nombre}" <#{email}>)
    }
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ayudantes_controller.rb
class AyudantesController < ApplicationController
  before_action :set_ayudante, only: [:show, :edit, :update, :destroy]

  # GET /ayudantes
  # GET /ayudantes.json
  def index
    @ayudantes = Ayudante.all
  end

  # GET /ayudantes/1
  # GET /ayudantes/1.json
  def show
  end

  # GET /ayudantes/new
  def new
    @ayudante = Ayudante.new
  end

  # GET /ayudantes/1/edit
  def edit
  end

  # POST /ayudantes
  # POST /ayudantes.json
  def create
    @ayudante = Ayudante.new(ayudante_params)

    respond_to do |format|
      if @ayudante.save
        format.html { redirect_to welcome_index_url, notice: 'Tu informacion ha sido guardada, te contactaremos lo mas pronto posible' }
        format.json { render :show, status: :created, location: @ayudante }
      else
        format.html { render :new }
        format.json { render json: @ayudante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ayudantes/1
  # PATCH/PUT /ayudantes/1.json
  def update
    respond_to do |format|
      if @ayudante.update(ayudante_params)
        format.html { redirect_to @ayudante, notice: 'Ayudante was successfully updated.' }
        format.json { render :show, status: :ok, location: @ayudante }
      else
        format.html { render :edit }
        format.json { render json: @ayudante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayudantes/1
  # DELETE /ayudantes/1.json
  def destroy
    @ayudante.destroy
    respond_to do |format|
      format.html { redirect_to ayudantes_url, notice: 'Ayudante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ayudante
      @ayudante = Ayudante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ayudante_params
      params.require(:ayudante).permit(:rut, :nombre, :apellido, :asignatura, :carrera, :email)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if( @contact.deliver)
			flash.now[:error] = nil
		else
			flash.now[:error] = 'No se pudo enviar el mensaje'
			render :new
		end
		
	end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ayudantes_helper.rb
module AyudantesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ayudantes/edit.html.erb
<h1>Editing Ayudante</h1>

<%= render 'form' %>

<%= link_to 'Show', @ayudante %> |
<%= link_to 'Back', ayudantes_path %>

app/views/ayudantes/index.html.erb
<%= link_to 'Volver al menu principal', welcome_index_path %>

app/views/ayudantes/new.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="css/style.css" media="screen,projection">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

<div  class="parallax-container">


         <div class="row ">
            	<div class= "center col s12 m4 l10">
            		<h3 class="header teal-text text-lighten-2">¡ Buscamos los mejores tutores !</h3>
            	</div>
					         <div class="row center"> 
						            <img src='<%= asset_path 'utem1.png' %>'class="responsive-img"  class="thumb"  width="110" height="110"/>
					         </div>
						       <div class="parallax"><%= image_tag("a93.jpg") %></div>
						            <div class=" row">
							             <div class= "center col s12 m4 l10">
								            <h5 class="header green-text text-darken-1">Ingresa tus datos para ponernos en contacto contigo.</h5>
							             </div>
						  </div>
		     </div>
      



<%= form_for(@ayudante) do |f| %>

<% if @ayudante.errors.any? %>

    <div class="center"  id="error_explanation">
		    <ul  id="dropdown2" class=" dropdown-content">
   			    <% @ayudante.errors.full_messages.each do |message| %>
        		<li><%= message %></li>
      			<% end %>
      	</ul>
  			<a class="btn dropdown-button red"  data-activates="dropdown2">Error al guardar<i ></i></a>
  	</div>
  

  <% end %>

	<div class="row">
        <div class="input-field col s5 text-lighten-4">
          <i class="material-icons prefix">account_circle</i>
          <label for="name">Nombre</label>
          </br>
          <%=f.text_field :nombre,:maxlength => 25%>
        </div> 
        
        <div class="input-field col s5">
          <i class="material-icons prefix">account_circle</i>
          <label class="text-lighten-4" for="lastname">Apellido</label>
          </br>
          <%=f.text_field :apellido,:maxlength => 25 %>
        </div>            
  </div>

    <div class="row">

           <div class=" input-field col s10  text-lighten-4">

              <div class="control-group">
                    <div class="controls">
                    
                     <i class="material-icons prefix">business </i>
                     
                     <%= f.select(:carrera, options_for_select([['Ingeniería Civil Electrónica/Mecánica','Ingeniería Civil Electrónica/Mecánica'],['Ingeniería Informática/Civil en Computación ', 'Ingeniería Informática/Civil en Computación'], ['Ingeniería Industrial/Civil Industrial', 'Ingeniería Industrial/Civil Industrial'],['Ingeniería Química/Química Industrial/Biotecnología','Ingeniería Química/Química Industrial/Biotecnología'], ['Ingeniería en Geomensura/Transporte y Tránsito','Ingeniería en Geomensura/Transporte y Tránsito'],['Otro','Otro']]), {  prompt: 'Seleccione Carrera' }) %>
                    </div>
              </div>
          </div>
      </div>


    <div class="row">
        <div class="input-field col s10 text-lighten-4">
          <i class="material-icons prefix">picture_in_picture</i>
          <label for="name">Rut (Ej:123456789-0)</label>
          </br>
          <%=f.text_field :rut,:maxlength => 30%>
        </div> 
    </div>
    <div class="row">
        <div class="input-field col s10">
          <i class="material-icons prefix">markunread_mailbox</i>
          <label for="email">Email</label>
          </br>
          <%=f.text_field :email%>
        </div>            
    </div>

     

       <div class="row">

           <div class=" input-field col s10  text-lighten-4">

              <div class="control-group">
                    <div class="controls">
                     <i class="material-icons prefix">spellcheck</i>

                     <%= f.select(:asignatura, options_for_select([['Algebra I', 'Algebra I'], ['Calculo I', 'Calculo I'],['Química General', 'Química General'], ['Física Clásica', 'Física Clásica'], ['Otro', 'Otro']]), {  prompt: 'Seleccione Asignatura a realizar' }) %>
                    </div>
              </div>
       		 </div>
       	</div>







    <div class="row">
           <div class = "button center col s5">
              	<%=f.submit "Guardar" ,class:"btn center-align"%>
           </div>
           		<div class = "button center col s5">
           			<%= link_to 'Volver', welcome_index_path, class:"btn center-align"%>
           		</div>
    </div>

  </div>
    




<%end%>   




</body>
</html>

app/views/ayudantes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de ayudantes</h1>

<table>
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Asignatura</th>
      <th>Carrera</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ayudantes.each do |ayudante| %>
      <tr>
        <td><%= ayudante.rut %></td>
        <td><%= ayudante.nombre %></td>
        <td><%= ayudante.apellido %></td>
        <td><%= ayudante.asignatura %></td>
        <td><%= ayudante.carrera %></td>
        <td><%= ayudante.email %></td>
        <td><%= link_to 'Destroy', ayudante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ayudante', new_ayudante_path %>

app/views/contacts/create.html.erb
<div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Su mensaje se ha enviado</span>
              <p>Nos estaremos poniendo en contacto contigo, recuerda que también puedes visitarnos en facebook y twitter. Esperamos que vuelvas a comunicarte con nosotros ante cualquier duda.</p>
            </div>
            <div class="card-action">
              <a <%= link_to "Volver al menu principal", welcome_index_path%> </a>
              <a href="https://youtube.com">Canal youtube</a>
            </div>
          </div>
        </div>
      </div>

app/views/contacts/new.html.erb
<div class="row">
<h4 class="header blue-text text-darken-2">Contactanos</h4>
</div>

<div class="parallax" class="responsive-img"><%= image_tag("a13.jpg") %></div>


	<%= form_for @contact do |f| %>

	<% if @contact.errors.any? %>

    <div class="center"  id="error_explanation">
		    <ul  id="dropdown2" class=" dropdown-content">
   			    <% @contact.errors.full_messages.each do |message| %>
        		<li><%= message %></li>
      			<% end %>
      	</ul>
  			<a class="btn dropdown-button red"  data-activates="dropdown2">Error al guardar<i ></i></a>
  	</div>

    <% end %>

    <div class="row">
        <div class="center input-field col s12 m6 blue-text text-darken-2">
          <%= f.label :nombre %><br />
          <%= f.text_field :nombre,:maxlength => 30%>
        </div> 
    </div>

    <div class="row">
        <div class="center input-field col s12 m6 blue-text text-darken-2">
          <%= f.label :email %><br />
          <%=f.text_field :email,:maxlength => 30%>
        </div> 
    </div>



		<br>
		<br>

		<div class="row">
              	<div class="input-field col s7 blue-text text-darken-2">         
                  <label for="name">Mensaje</label>
                  </br></br>
                  <%=f.text_area :mensaje %>
        		</div>
        </div>


		<br>

		<div class="row">
           <div class = "button center col s5">
              <%=f.submit "Enviar" ,class:"btn center-align"%>
            </div>
        </div>

	<% end %>

app/views/info/index.html.erb
<div class="parallax" class="responsive-img"><%= image_tag("a13.jpg") %></div>
<div class="center row">
      <div class="col s12 ">
        <div class="card-panel teal">
          <span class="white-text">De la mano del gobierno de Chile, a través del FDI(Fondo de Desarrollo Institucional),se nos ha otorgado el privilegio de realizar nuestra propuesta llamada "Videotutores", que consiste en centrar el estudio de cientos de estudiantes de primer año de ingeniería de la sede Macul en la universidad UTEM, a través de videos con contenido relevante de pruebas y materia de los ramos más complejos, para ello contaremos con ayudantes capacitados que los guiarán en todo el proceso.
          </span>
        </div>
      </div>
    </div>
<div class="center row">
      <div class="col s12 ">
        <div class="card-panel  pink darken-4">
          <span class="white-text">Somos un grupo de estudiantes de la sede Macul, quienes estamos a cargo de coordinar el contenido, edición y ejecución de los videos, en su mayoría validados con profesores. Nuestra única misión es ayudar al estudiante que viene ingresando a la universidad, otorgándoles herramientas de conocimiento. Queremos disminuír la taza de reprobados en los ramos más difíciles, es por ello la iniciativa de incluír a la misma gente dentro de la universidad.
          </span>
        </div>  
    </div> 
</div>

<div class="row">
<div class = "button center s12 m4 l8">
           			<%= link_to 'Volver', welcome_index_path, class:"btn center-align"%>
          </div>
           		</div>


    
    
  

 
    </body>
    </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>




<div class="navbar-fixed" >
    <nav>
      <div class=" nav-wrapper blue-grey lighten-4" >
      
       
        <ul class="center ">
          <div class= "col s12 m6">
              <li><a href="https://facebook.com"><i class="  material-icons"><%= image_tag("fb3.png", :alt => "rss feed") %></i></a></li>
              <li><a href="https://twitter.com"><i class="material-icons"><%= image_tag("tw1.png", :alt => "rss feed") %></i></a></li>
              <li><a href="https://youtube.com"><i class="material-icons"><%= image_tag("you1.png", :alt => "rss feed") %></i></a></li>
          </div>
        </ul>
      </div>
    </nav>

</div>










<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script> 
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


<%= yield %>
  

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel='stylesheet'>
  
  

<body>


  <div id="index-banner" class="parallax-container">
          <div class="section no-pad-bot">
                 <div class="container ">
                       <br><br>
                       <div class="container">
                             <div id="notice_wrapper">
                                <% if notice %>
                                <p class="notice"><%= notice %></p>
                                <% elsif alert %>  
                                <p class="alert"><%= alert %></p>
                                <% end %>   
                             </div>
                        </div>  


          <div class="col s12 m6">
              <h3 class="header center teal-text text-lighten-2">VIDEOTUTORES</h3>
                <div class="row center">
                  <h5 class="header col s12 light">¿Quieres ser parte de este novedoso proyecto?</h5>
                </div>
                  <div class="row center">
                      <%= link_to "¡Quiero Unirme!", new_ayudante_path(@ayudante), class: "btn-large waves-effect waves-light teal lighten-2" %>
                  </div>          
          </div>
                  <br><br>
      </div>
    </div>
    <div class="parallax"><%= image_tag("a3.jpg") %></div>
    </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m6">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">stars</i></h2>
            <h5 class="header center teal-text text-lighten-2">Nuestro Objetivo</h5>

            <p class="light">Te enseñamos de una manera diferente, intuitiva y eficaz. El mundo actual requiere de personas capaces de trasmitir conocimiento, y nosotros estamos a la vanguardia, para que tengas la mejor experiencia estudiando con nosotros.</p>
            <div class="row center">
            <%= link_to "mas informacion", info_index_path, class: "btn-large waves-effect waves-light green lighten-3" %>
                
            </div>

          </div>
        </div>


        <div class="col s12 m6">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">email</i></h2>
            <h5 class="header center teal-text text-lighten-2">¿Necesitas Ayuda?</h5>
            <p class="light">Envíanos un mensaje para que podamos resolver tus inquietudes, recuerda que estamos disponibles todos los días del año. Nuestros ayudantes se encargarán de proporcionarte la ayuda que necesitas </p> 
            <div class="row center">
                <%= link_to "contactanos", contacts_new_path, class: "btn-large waves-effect waves-light green lighten-3" %>
            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
  

 <script>$(document).ready(function(){
    $('.parallax').parallax();
});
</script>
</body>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Nuestro Legado</h5>
          <p class="grey-text text-lighten-4">Equipo de desarrollo formado para crear un apoyo directo a estudiantes de nuestra universidad UTEM y para todos quienes tengan el deseo de aprender a través de videos con ayudantes capacitados.</p>
        </div>
          <div class="col l3 s12"></div>
          <div class="col l3 s12">
              <h5 class="white-text">Lugares de interés</h5>
              <ul>
                <li><a class="white-text" href="http://www.utem.cl">UTEM.CL</a></li>
                <li><a class="white-text" href="http://reko.utem.cl">REKO</a></li>
                <li><a class="white-text" href="http://dirdoc.utem.cl">DIRDOC</a></li>
                <li><a class="white-text" href="http://mi.utem.cl/">MI.UTEM</a></li>
              </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Desarrollado por: <a class="brown-text text-lighten-3" href="">Ariel Vargas</a>
      </div>
    </div>
  </footer>
  





</html>